### ISSUE TITLE
Gayanukiththa is super wierd

### ISSUE THREAD

**Issue by pathumego** [mooniak/ayanna-font#20]
<img width="153" alt="screen shot 2015-11-03 at 11 52 22 am" src="https://cloud.githubusercontent.com/assets/6846609/10907383/6c08d652-8221-11e5-8bd7-ba4b82dda8f5.png">

**Comment by DenzelRajitha** [comment]
fixed with commit 827a861b0a59195ef9c0d21c5ec90ef9932d95d1
