### ISSUE TITLE
Yansaya proportions and nose

### ISSUE THREAD

**Issue by pathumego** [mooniak/ayanna-font#22]
Yansaya is weird because of few reasons, proportions and relationship between strokes are off. ANd nose is twisted as i highlighted.

<img width="199" alt="screen shot 2015-11-03 at 11 58 23 am" src="https://cloud.githubusercontent.com/assets/6846609/10907484/53e26858-8222-11e5-94ca-5442cf39b417.png">
<img width="228" alt="screen shot 2015-11-03 at 11 58 36 am" src="https://cloud.githubusercontent.com/assets/6846609/10907483/53e198ce-8222-11e5-82a2-605f781ae953.png">
<img width="292" alt="screen shot 2015-11-03 at 11 59 01 am" src="https://cloud.githubusercontent.com/assets/6846609/10907485/53e2846e-8222-11e5-8e72-db68f8858218.png">

<img width="199" alt="screen shot 2015-11-03 at 11 58 23 am" src="https://cloud.githubusercontent.com/assets/6846609/10907509/948e4584-8222-11e5-8072-22fdc6619de6.png">
<img width="228" alt="screen shot 2015-11-03 at 11 58 36 am" src="https://cloud.githubusercontent.com/assets/6846609/10907510/94b3154e-8222-11e5-9bad-f7a57e1701d7.png">

Moving the stroke a bit further up would help the nose issue.

**Comment by DenzelRajitha** [comment]
fixed with commit 827a861b0a59195ef9c0d21c5ec90ef9932d95d1
