### ISSUE TITLE
Latin build fail

### ISSUE THREAD

**Issue by pathumego** [mooniak/ayanna-font#24]
@paarandika PLease check and let me knwo what is the problem. The build files are not valid. Check gh-pages for files

**Comment by pathumego** [comment]
@DenzelRajitha PLease add `.notdef` glyph to both Sinhala masters

**Comment by paarandika** [comment]
There are Sinhala and Tamil glyphs in Latin ufo. @pathumego Can you remove them? And there is a confusion with zero width joiner(zwj), zero width non joiner (zwnj) and zero width no break space (zwnbs). Please correct it too.

**Comment by pathumego** [comment]
Fixed
