### ISSUE TITLE
/anuswara is too small

### ISSUE THREAD

**Issue by pathumego** [mooniak/ayanna-font#29]
<img width="290" alt="screen shot 2015-11-17 at 4 16 49 pm" src="https://cloud.githubusercontent.com/assets/6846609/11217128/abbeb0f2-8d46-11e5-9f76-3bb28f45c56c.png">

**Comment by DenzelRajitha** [comment]
fixed with commit 827a861b0a59195ef9c0d21c5ec90ef9932d95d1
