### ISSUE TITLE
Vertical spacing errors

### ISSUE THREAD

**Issue by paarandika** [mooniak/ayanna-font#37]
![3a](https://cloud.githubusercontent.com/assets/6725097/12372373/e0583f42-bc79-11e5-854d-5e558396b782.PNG)
![1a](https://cloud.githubusercontent.com/assets/6725097/12372374/e05b9db8-bc79-11e5-8b19-35db7effca75.PNG)
![2a](https://cloud.githubusercontent.com/assets/6725097/12372375/e05eadd2-bc79-11e5-8d1f-cd52c2f94f27.PNG)
We have number of issues with vertical spacing. Specially these kind of collisions may occur when using characters of different languages together(eg: Tamil and Sinhala).I have used the values:
```python
TypoAscender 750;
TypoDescender -250;
TypoLineGap 213;
winAscent 960;
winDescent 253;
hhea Ascender 960;
hhea Descender -253;
```

**Comment by davelab6** [comment]
You should set the values to the bbox of the family. 

There is a fontbakery script that will print the vertical metrics of a set of font, and fix them. 

    ls -l *.ttf;
    fontbakery-fix-vertical-metrics.py *.ttf;
    fontbakery-fix-vertical-metrics.py --autofix *.ttf;
    ls -l *.ttf.fix;

**Comment by paarandika** [comment]
No. I just used the values you have suggested [here](https://github.com/mooniak/abhaya-libre-font/issues/20)
I will try the fontbackery script and see. Thanks :)

**Comment by davelab6** [comment]
Yeah I'm not sure if that recommendation is good...

**Comment by khaledhosny** [comment]
Using font bounding box is not always a good idea it can either be too big (not common in text fonts) or two small (common in scripts where vertical stacking happens since the line height can easily exceed the bounding box of individual unstacked glyphs).

**Comment by paarandika** [comment]
![backk](https://cloud.githubusercontent.com/assets/6725097/12375014/9a4c5176-bcd5-11e5-9328-df2784435d5f.PNG)
Fontbackery suggest the same values I have used.
@khaledhosny What should I use to calculate correct values?

**Comment by davelab6** [comment]
But not doing so will cause clipping.

**Comment by davelab6** [comment]
No, it doesn't; it shows the value only.

Use the --autofix arg to create .fix files

**Comment by khaledhosny** [comment]
If the bbox is too small (which is likely the case here) using it *will cause* clipping, not the other way around. Using the bbox works when all glyphs are on the base line, but when yous start stacking glyphs vertically it can’t account for the vertical shift.

To answer @paarandika question, I set the Win metrics values to big enough values that I think won’t cause clipping (say by considering the height/depth of the biggest stacked combinations that seem likely), this obviously might not prevent all clipping, but using font metrics to clip text is such a brain dead idea that we can’t really 100% fix, other than by using ridiculously large Win metrics. That have the side effect of causing bad line spacing in messed up application that abuse Win metrics for this, but there is nothing one can do here.

and set the typo metrics to values that avoid collisions most o time (which you can only find by testing large amounts of text). This does not have to fix all collisions, bit just to be good enough as a default for common cases. People setting text with unusually stacked glyphs will need to change the line spacing, but this should be OK especially on the web.

**Comment by EbenSorkin** [comment]
It is safe to have fairly large vertical metrics values on the web now. It wasn't always that way. If you want the font to work well everywhere then you will have to test to see what breaks where. I agree with Khaled, it is a good idea to find something that works to give you a pleasant if slightly generous setting 95% + of the time. For the 5% that cause problems look again at if you can alter the design itself via gentle scaling and or glyphs alteration to avoid them. But it is also a good idea to think carefully about  how big a problem it will really be. Letting a very rare event ruin what is otherwise excellent may not make sense.

**Comment by pathumego** [comment]
@paarandika Are we good with this?

**Comment by paarandika** [comment]
Seems so. I used the values suggested by fontbakery as
```python
hhea.Ascender 974;
hhea.Descender -387;
hhea.LineGap 0;
TypoAscender 974;
TypoDescender -387;
TypoLineGap 0;
winAscent 974;
winDescent 387;
```
Seems to work fine on MS Word and Chrome. But have to test little bit more.

**Comment by pathumego** [comment]
Ok  Thanks! @EbenSorkin @khaledhosny @davelab6  Randika will probably write small blog post on this, compiling your comments. And post on DWFF probably.
