### ISSUE TITLE
Two extra glyph slots

### ISSUE THREAD

**Issue by pathumego** [mooniak/ayanna-font#39]
Please remove these seen in the final built files. 

<img width="231" alt="screen shot 2016-01-20 at 1 59 05 pm" src="https://cloud.githubusercontent.com/assets/6846609/12450863/0b17b9a4-bf7e-11e5-809c-9b6597c7a336.png">

**Comment by pathumego** [comment]
Im not sure where these are coming from could be from Sinhala or tamil masters check all four files and use remove encoding slots.

**Comment by paarandika** [comment]
Tamil

**Comment by pathumego** [comment]
@kosalaya these glyphs are still present

**Comment by pathumego** [comment]
@paarandika I think the script dose not clean the merged masters before new build. So extra glyphs might not be removed even if we delete these from the SFD's

**Comment by paarandika** [comment]
Is that FF you you use to examine these things?

**Comment by pathumego** [comment]
Yes, Ill check again now

**Comment by pathumego** [comment]
This was caused by a bug in build where it did not delete the removed glyphs in master ufo's. Was fixed with 20a977a
